/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

/**
 *
 * @author Usuario
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnVerdeC = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbLegendaLogoC = new java.awt.Label();
        pnBrancoC = new javax.swing.JPanel();
        lbLogin = new javax.swing.JLabel();
        lbNomec = new javax.swing.JLabel();
        campoNomeC = new javax.swing.JTextField();
        lbSenhaC = new javax.swing.JLabel();
        campoSenhaC = new javax.swing.JPasswordField();
        btnEntrarC = new javax.swing.JButton();
        lbLoginCadastroC = new java.awt.Label();
        btnCadastroLoginC = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        pnVerdeC.setBackground(new java.awt.Color(17, 67, 46));
        pnVerdeC.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formulario/somensageLg.png"))); // NOI18N

        lbLegendaLogoC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbLegendaLogoC.setForeground(new java.awt.Color(255, 255, 255));
        lbLegendaLogoC.setText("Onde toda conversa começa bem ");

        javax.swing.GroupLayout pnVerdeCLayout = new javax.swing.GroupLayout(pnVerdeC);
        pnVerdeC.setLayout(pnVerdeCLayout);
        pnVerdeCLayout.setHorizontalGroup(
            pnVerdeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVerdeCLayout.createSequentialGroup()
                .addGroup(pnVerdeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnVerdeCLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbLegendaLogoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnVerdeCLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pnVerdeCLayout.setVerticalGroup(
            pnVerdeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVerdeCLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lbLegendaLogoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pnBrancoC.setBackground(new java.awt.Color(255, 255, 255));
        pnBrancoC.setPreferredSize(new java.awt.Dimension(400, 500));

        lbLogin.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(17, 67, 46));
        lbLogin.setText("CADASTRO");

        lbNomec.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNomec.setText("Nome");

        campoNomeC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoNomeC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbSenhaC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbSenhaC.setText("Senha");

        campoSenhaC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoSenhaC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnEntrarC.setBackground(new java.awt.Color(17, 67, 46));
        btnEntrarC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEntrarC.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrarC.setText("Cadastrar");

        lbLoginCadastroC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbLoginCadastroC.setText("Não tem uma conta");

        btnCadastroLoginC.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastroLoginC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCadastroLoginC.setForeground(new java.awt.Color(0, 102, 255));
        btnCadastroLoginC.setText("Login");
        btnCadastroLoginC.setBorder(null);

        label1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label1.setText("Número de Telefone");

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnBrancoCLayout = new javax.swing.GroupLayout(pnBrancoC);
        pnBrancoC.setLayout(pnBrancoCLayout);
        pnBrancoCLayout.setHorizontalGroup(
            pnBrancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBrancoCLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(pnBrancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBrancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnBrancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBrancoCLayout.createSequentialGroup()
                                .addGroup(pnBrancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSenhaC)
                                    .addComponent(lbNomec))
                                .addGap(308, 308, 308))
                            .addGroup(pnBrancoCLayout.createSequentialGroup()
                                .addGroup(pnBrancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnBrancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(campoNomeC, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoSenhaC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                                    .addComponent(btnEntrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()))
                        .addGroup(pnBrancoCLayout.createSequentialGroup()
                            .addGroup(pnBrancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnBrancoCLayout.createSequentialGroup()
                                    .addComponent(lbLoginCadastroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCadastroLoginC))
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBrancoCLayout.createSequentialGroup()
                        .addComponent(lbLogin)
                        .addGap(120, 120, 120))))
        );
        pnBrancoCLayout.setVerticalGroup(
            pnBrancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBrancoCLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbLogin)
                .addGap(61, 61, 61)
                .addComponent(lbNomec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbSenhaC)
                .addGap(18, 18, 18)
                .addComponent(campoSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEntrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBrancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbLoginCadastroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastroLoginC))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnVerdeC, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBrancoC, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnBrancoC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnVerdeC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroLoginC;
    private javax.swing.JButton btnEntrarC;
    private javax.swing.JTextField campoNomeC;
    private javax.swing.JPasswordField campoSenhaC;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Label lbLegendaLogoC;
    private javax.swing.JLabel lbLogin;
    private java.awt.Label lbLoginCadastroC;
    private javax.swing.JLabel lbNomec;
    private javax.swing.JLabel lbSenhaC;
    private javax.swing.JPanel pnBrancoC;
    private javax.swing.JPanel pnVerdeC;
    // End of variables declaration//GEN-END:variables
}
